### ISSUE TITLE
crates.io/si

### ISSUE THREAD

**Issue by kpp** [iliekturtles/uom#101]
Hi. I may transfer https://crates.io/crates/si to you, because I was lazy to implement it on my own. How about extracting mod si into a standalone crate?

**Comment by iliekturtles** [comment]
Thanks for the offer, however I'm planning on sticking with `uom` for now. I've been thinking a little bit about splitting the SI implementation into a stand-alone crate and was going to use `uom-si` if I did (I'll open a separate issue).

You could add a big note to the top of your README and push to crates.io saying that you're willing to transfer if someone else is interested in the crate name.

**Comment by kpp** [comment]
I will. Thanks.

Anyway you are welcome to get it.
