### ISSUE TITLE
Consider moving SI implementation into separate crate

### ISSUE THREAD

**Issue by iliekturtles** [iliekturtles/uom#102]
Likely named `uom-si`. Looking for feedback at this point.

**Comment by Aehmlo** [comment]
I think using just SI and not the other functionality (custom systems) is a pretty common use case, but I'm not sure how much benefit there is to such a split. I certainly wouldn't say that this is a harmful thing, but would you mind listing your rationale briefly?

**Comment by iliekturtles** [comment]
I'm not sure there really is much benefit except for users who don't want the built-in system. This may change if custom derive is needed at some point as my understanding is that multiple crates are needed in this case.

**Comment by Aehmlo** [comment]
> I'm not sure there really is much benefit except for users who don't want the built-in system.

Isn't that what the `si` feature is for?

**Comment by iliekturtles** [comment]
Closing this issue. I haven't really found a great reason to split the SI into a separate crate.
