### ISSUE TITLE
New SI

### ISSUE THREAD

**Issue by Aehmlo** [iliekturtles/uom#111]
In 2019, the International System of Units [will be getting a revamp](https://en.wikipedia.org/wiki/2019_redefinition_of_SI_base_units). Hooray precision!

I’m not sure if it’d be better to just jump onto the new definition or to give an option for it, but something’s probably going to have to happen. I’m sure it was probably already on your radar, but here’s an issue anyway.

**Comment by iliekturtles** [comment]
I heard about the vote but hadn't read any further. The old and new base unit definitions don't affect `uom`, but I wasn't sure if any conversion factors change which would affect `uom` and call for a new feature.

**Comment by Aehmlo** [comment]
Yeah, I expect some conversions between systems would have to change, although I also haven't dived into it yet.
