### ISSUE TITLE
Document example of argument passing

### ISSUE THREAD

**Issue by d6y** [iliekturtles/uom#113]
Hello and thanks for making this crate. 

I'd find it useful to add an example of passing dimensions to functions. For example, something like `speed` in this modification of the "hello world"...

```
extern crate uom;

use uom::si::f32::*;
use uom::si::length::kilometer;
use uom::si::time::second;

fn main() {
    let length = Length::new::<kilometer>(5.0);
    let time = Time::new::<second>(15.0);
    let velocity = speed(length, time);
    println!("Average speed was: {:?}", velocity);
}

fn speed(length: Length, time: Time) -> Velocity {
    length / time
}

```

...assuming that's right, which is a big assumption! (hey, it compiles, what can posibly go wrong).

**Comment by iliekturtles** [comment]
Thanks for the suggestion! I'll see about an example like this tonight.

**Comment by iliekturtles** [comment]
Changes in 06d2c70. Let me know what you think.

**Comment by d6y** [comment]
@iliekturtles looks good to me. Thank you 🎉
