### ISSUE TITLE
Building Momentum

### ISSUE THREAD

**Issue by dunmatt** [iliekturtles/uom#114]
Would you be open to a PR that adds Momentum (kg*m/s) to uom?  If not, is there a recommended way of dealing with momentum?

Edit: same questions for Torque (Nm)

**Comment by iliekturtles** [comment]
I'd love PRs for momentum and torque. Let me know if you need any guidance to get started. [NIST 811 appendix B9](https://www.nist.gov/pml/nist-guide-si-appendix-b9-factors-units-listed-kind-quantity-or-field-science) has a number of units for torque. Momentum isn't listed so I suggest adding combinations of the most common si prefixes along with common non-si units (e.g. slug ft/s). Also see https://github.com/iliekturtles/uom/blob/master/src/si/mass_rate.rs for some good test examples.

**Comment by dunmatt** [comment]
Is torque going to run into a problem since it has the same base units as energy?

**Comment by iliekturtles** [comment]
Nope! Specify a new `Kind` for torque. See [temperature interval](https://github.com/iliekturtles/uom/blob/master/src/si/temperature_interval.rs) and [thermodynamic temperature](https://github.com/iliekturtles/uom/blob/master/src/si/thermodynamic_temperature.rs) for an example how to do this. I haven't done any research to see what a good kind name is. Perhaps just `Torque`. The new kind will likely want to implement all of the [marker traits](https://github.com/iliekturtles/uom/blob/master/src/lib.rs#L261).

**Comment by dunmatt** [comment]
Oooh, I've never used a `Kind` before (although I have vague memories of being taught about them in grad school)... exciting!
