### ISSUE TITLE
Implement Display, LowerExp, UpperExp, ...

### ISSUE THREAD

**Issue by iliekturtles** [iliekturtles/uom#13]
https://doc.rust-lang.org/core/fmt/trait.Binary.html
https://doc.rust-lang.org/core/fmt/trait.Display.html
https://doc.rust-lang.org/core/fmt/trait.LowerExp.html
https://doc.rust-lang.org/core/fmt/trait.LowerHex.html
https://doc.rust-lang.org/core/fmt/trait.Octal.html
https://doc.rust-lang.org/core/fmt/trait.UpperExp.html
https://doc.rust-lang.org/core/fmt/trait.UpperHex.html

Is there a way to use the [fmt](https://doc.rust-lang.org/core/fmt/) syntax or flags to include an implicit unit conversion, unit abbreviation, or unit label?

```rust
// What replaces `...` to allow the following outputs: 10 m, 10 meters, 32.8084 ft, 32.8084 feet
println!("{...}", new Length(10, meter));
```

 - [ ] `Quantity`
 - [ ] `$quantities` (Dimension)
 - [ ] `BaseUnits`
 - [ ] `$unit` (Measurement units)

**Comment by iliekturtles** [comment]
Something like the following should be able to meet the requirements. Note that the following code takes a lot of liberties and is just to give an idea of what should be necessary.

The `Arguments` struct would contain `uom` specific formatting settings like the subunit to display and how to label the value. Numeric formatting options would still come from the format string and be pushed down to the underlying storage type's `Display`/`LowerExp`/... implementation.

```rust
mod fmt {
    pub struct Arguments<...> {
        subunit: Subunit,
        label: LabelEnum,
    }

    pub struct QuantityArguments<...> {
        quantity: Quantity<...>,
        arguments: Arguments,
    }

    impl Display for Arguments { ... }
    impl LowerExp for Arguments { ... }
    ...
}

...

let l = Length::<meter>::new(10);
let a1: Arguments = Arguments::new(meter, Abbreviation);
let a2: Arguments = Arguments::new(meter, Description);
let a3: QuantityArguments = Arguments::new(l, foot, Abbreviation);
let a4: QuantityArguments = Arguments::new(l, foot, Description);

// 10 m, 10 meters, 32.8084 ft, 32.8084 feet
println!("{}, {}, {}, {}", a1.with(l), a2.with(l), a3, a4);
```

**Comment by iliekturtles** [comment]
Not exactly sure what you mean by printing raw units. Can you provide a short example?

**Comment by Aehmlo** [comment]
Something like `println!("{}", meter)`, perhaps with the same options for the output to be "meter"/"m".

**Comment by iliekturtles** [comment]
Ahhh. Not needed! `meter.abbreviation()/.singular()/.description()` can be used.

**Comment by Aehmlo** [comment]
That's what I figured. PR inbound soon.
