### ISSUE TITLE
AngleKind errors when multiplying by f64s

### ISSUE THREAD

**Issue by dunmatt** [iliekturtles/uom#138]
It looks like we missed something:

    let compiles_fine = 5.0 * Angle::new::<radian>(1.0);
    let wont_compile: Angle = 5.0 * Angle::new::<radian>(1.0);
    let hacky: Angle = (5.0 * Angle::new::<radian>(1.0)).into();

throws Kind mismatch errors, apparently floats times quantities always returns a regular Kind rather than AngleKind.  I'm going to look for a fix, if you don't see a PR in the next day or two assume that I got stuck somewhere and could use a hint.

**Comment by iliekturtles** [comment]
Issue is that the `impl $MulDiv<Quantity> for V` doesn't maintain the kind when calculating the new dimension. Maintaining the kind is simple but does it make sense for all cases?

```rust
// Will work as expected
let a: Angle = 5.0 * Angle::new::<radian>(1.0);

// Should `b` have a kind of `AngleKind`?
let b = 5.0 / Angle::new::<radian>(1.0);
```

Patch to fix issue:

```diff
diff --git a/src/system.rs b/src/system.rs
index fa0122c..87a8a04 100644
--- a/src/system.rs
+++ b/src/system.rs
@@ -510,7 +510,8 @@ macro_rules! system {
                                 $quantities<
                                     $($crate::typenum::$AddSubAlias<
                                       $crate::typenum::Z0,
-                                      D::$symbol>,)+>,
+                                      D::$symbol>,)+
+                                    D::Kind>,
                                 U, V>;

                             #[inline(always)]
```

**Comment by dunmatt** [comment]
I think so, because 

    let c = Angle::new::<radian>(1.0) / 5.0;

had better be an `Angle`, and `b` ought to be its reciprocal.

**Comment by iliekturtles** [comment]
`impl $MulDiv<V> Quantity` already maintains the kind: https://github.com/iliekturtles/uom/blob/def7d69cb40224adbdc59721dc4b141df83bc317/src/system.rs#L464-L471

I'll get the patch above committed and merged once the build completes. I'll also see about releasing a new version today or tomorrow before I lose internet access for a bit.

**Comment by dunmatt** [comment]
Awesome, thanks!
