### ISSUE TITLE
Quantity should be `repr(transparent)`

### ISSUE THREAD

**Issue by gnzlbg** [iliekturtles/uom#145]
Is there a reason why this is not the case ? Without `repr(transparent)` `Quantity` has a struct ABI, instead of the ABI of `T` (scalar float or scalar integer). This means that one cannot use `Quantity` in C FFI, and it also might mean that the compiler might generate sub-optimal code for those situations in which the struct ABI is worse than the float or integer one.

**Comment by iliekturtles** [comment]
Looks like work in `rustc` prior to 1.28.0, when `#repr[transparent]` was stabilized, fixed this issue (https://github.com/rust-lang/rust/issues/38269) in pure Rust and I never added `#repr[transparent]` for FFI once it stabilized. I'll bump `uom`'s minimum rustc version and then merge your PR. Thanks!
