### ISSUE TITLE
Support trigonometric functions on Angles

### ISSUE THREAD

**Issue by neganp** [iliekturtles/uom#151]
Is there a good way to support trigonometric functions on `Angle` quantities? It seems like converting them to radians in floating point, calling the relevant `std` trig function, and returning a `Ratio` quantity (with `Result`s in the right places to deal with Floating Point Weirdness and domain violations) would be useful.

If that's something that wouldn't be too hard to implement, I could try to add it.

**Comment by iliekturtles** [comment]
This can be done and I've been meaning to add a new issue with details but haven't had time. See https://github.com/iliekturtles/uom/pull/144#issuecomment-499204853 where this was discussed recently. If you want to submit a PR that would be great!

**Comment by neganp** [comment]
Great to hear 😄.

I'll see if I can get one method working and open a WIP pull request so there's something concrete to comment on.
