### ISSUE TITLE
SI does not define a year, and current definition isn't accurate

### ISSUE THREAD

**Issue by ChristopherRabotin** [iliekturtles/uom#180]
I could not find a SI definition for a year in the [SI Brochure](https://www.bipm.org/utils/common/pdf/si-brochure/SI-Brochure-9.pdf). However, version [0.27](https://docs.rs/uom/0.27.0/src/uom/si/time.rs.html#51) defines a year as 365.0 days of 86 400 seconds. If a year is defined in the uom library, I reckon it should be 365.25 days of 86400 seconds, which is the most accurate definition of a year (and why there is a leap day every four years, with some exceptions).

**Comment by iliekturtles** [comment]
https://www.nist.gov/pml/special-publication-811/nist-guide-si-appendix-b-conversion-factors/nist-guide-si-appendix-b9#TIME

`uom` just has the definition of a 365 day year. We should probably add the sidereal and tropical definitions. These come out to 365.256 and 365.242 days respectively.

**Comment by ChristopherRabotin** [comment]
I didn't know about these NIST definitions.

**Comment by iliekturtles** [comment]
Sidereal and tropical time definitions added in #182. Let me know if you end up wanting these definitions on crates.io and I'll push a new release. Otherwise I'm going to hold off for more changes.
