### ISSUE TITLE
Change trigonometric functions to return Ratio?

### ISSUE THREAD

**Issue by iliekturtles** [iliekturtles/uom#185]
See https://github.com/iliekturtles/uom/issues/168#issuecomment-552442990. Should the existing trigonometric functions on `Angle` be changed to return `Ratio` instead of the underlying storage type?

**Comment by adamreichold** [comment]
I think we should switch to `Ratio` indeed: For symmetry with the inverse functions which we cannot define on the underlying storage type and to stay within the uom-typed universe. The main downside I see is the resulting breakage for little practical gain.
