### ISSUE TITLE
Remove From/Into impls for Angle?

### ISSUE THREAD

**Issue by iliekturtles** [iliekturtles/uom#188]
The impls were included as part of the original PR that added `Angle`. As @adamreichold brings up in #187 these are a potential source of errors as they assume that the value is always in radians.

@dunmatt Do you remember why the impls were added? Does your code use them?

https://github.com/iliekturtles/uom/blob/bdb73723da75a392aeb3f4d7afd1ce05af30886f/src/si/angle.rs#L95-L125

**Comment by adamreichold** [comment]
Any news on this? Note that while I have added the same conversions to `SolidAngle` for consistency I would still prefer if both of them were removed. Also note that `Information` does not provide those conversions either.

**Comment by iliekturtles** [comment]
Sorry for the delay, I was gone for a long weekend. There has been no feedback from dunmatt since the issue was opened so I created PR #197. If you could review my work that would be great. I'll also see about pushing out a new release to crates.io at some point this week.
