### ISSUE TITLE
Add support for solid angles and steradian

### ISSUE THREAD

**Issue by adamreichold** [iliekturtles/uom#190]
While the SI system supports angles measured in e.g. radians, it currently does not support solid angles measured in e.g. steradians.

**Comment by iliekturtles** [comment]
If anyone is interested in picking up this issue the new `SolidAngle` quantity should have a kind of `SolidAngleKind` to differentiate it from other dimensionless quantities.

Example from `Angle` which has a kind of `AngleKind`:
https://github.com/iliekturtles/uom/blob/0bc0b92e1ecaaaf3f8ccfbd1894aa022051dcca3/src/si/angle.rs#L18
