### ISSUE TITLE
Conversion between `ThermodynamicTemperature` units

### ISSUE THREAD

**Issue by valmirjunior0088** [iliekturtles/uom#195]
I'm having a hard time finding the correct way to convert a `ThermodynamicTemperature` from kelvin to celsius. Is there an example I could follow?

**Comment by iliekturtles** [comment]
The way `uom` works is that you only need to care about units (`celsius`, `kelvin`) when constructing a quantity (`ThermodynamicTemperature`) or extracting the value back out. I've put a simple example below that creates a couple `ThermodynamicTemperature`s from floats and then prints them out in different units. Let me know if this answers your questions. If so any feedback about how to update the documentation would be greatly appreciated.

```rust
extern crate uom;

use uom::si::f32::*;
use uom::si::thermodynamic_temperature::{degree_celsius, kelvin};
use uom::fmt::DisplayStyle::*;

fn main() {
    let t1 = ThermodynamicTemperature::new::<kelvin>(15.0);
    let t2 = ThermodynamicTemperature::new::<degree_celsius>(15.0);
    let a1 = ThermodynamicTemperature::format_args(kelvin, Abbreviation);
    let a2 = ThermodynamicTemperature::format_args(degree_celsius, Abbreviation);

    println!("a1.with(t1): {}", a1.with(t1));
    println!("a2.with(t1): {}", a2.with(t1));
    println!("a1.with(t2): {}", a1.with(t2));
    println!("a2.with(t2): {}", a2.with(t2));
}
```

Outputs the following:

```
a1.with(t1): 15 K
a2.with(t1): -258.15 °C
a1.with(t2): 288.15 K
a2.with(t2): 15 °C
```

**Comment by valmirjunior0088** [comment]
Oh. That does answer my question. Thanks!

My biggest hurdle was that I was intuitively trying to look into the `Conversion<T>` trait, but when I tried to follow its link, it led to a nonexistent page. I didn't even know the `.with()` method existed.

**Comment by valmirjunior0088** [comment]
One more question: Is it possible to obtain just the value in the target unit, without a `Description` or `Abbreviation`?

**Comment by iliekturtles** [comment]
The `get` method does this:

```rust
let c = t1.get::<degree_celsius>()
```

There is an existing issue, #123, to improve documentation for string formatting. Part of that should probably include differentiating between format (`-> String`) vs `get` (`-> <underlying storage type>`). I'll also note in that issue to update some of the examples (https://github.com/iliekturtles/uom/tree/master/examples) to include string formatting instead of `.get()`.

**Comment by valmirjunior0088** [comment]
Thank you very much! This solves my problem completely.
