### ISSUE TITLE
Doesn't compile on latest Rust

### ISSUE THREAD

**Issue by danielzgtg** [iliekturtles/uom#210]
`uom` doesn't compile on latest Rust.

# Rust Version

```
$ rustup update
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: checking for self-updates

  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.49.0-nightly (91a79fb29 2020-10-07)

info: cleaning up downloads & tmp directories
```

# Example project

```bash
cargo new test123
cd test123
echo 'uom = "0.29.0"' >> Cargo.toml
cargo build 2>&1 | tee log.txt
```

# Build error

[log.txt](https://github.com/iliekturtles/uom/files/5351467/log.txt)

**Comment by iliekturtles** [comment]
Thanks for the report. I'm setting up a minimally reproducible example to find out if this is a `uom` bug or something that should be reported upstream.

**Comment by iliekturtles** [comment]
Reported upstream: https://github.com/rust-lang/rust/issues/77638#issuecomment-706153295. Explicit bounds can be added to resolve the issue in `uom`, but I'm going to wait until discussion completes in the issue above to determine if this is the right solution.

**Comment by iliekturtles** [comment]
Per rust-lang/rust#77638 this isn't going to be fixed upstream. Working on a fix in `uom` now. I'm planning to release a new version to crates.io once this is completed.

**Comment by iliekturtles** [comment]
Code changes completed, but I ran out of time writing the commit message. Will try to get a PR pushed tomorrow.

**Comment by iliekturtles** [comment]
Thanks again for the report. v0.30.0 just published to crates.io with this fix.
