### ISSUE TITLE
Supporting user-defined string parsing

### ISSUE THREAD

**Issue by bheisler** [iliekturtles/uom#212]
uom's `Quantity::from_str` implementation is quite strict. It requires a number, a space and then an abbreviated unit. It does not support strings like "100g" or even "100 grams", even though these are natural ways for humans to write measurements.

I have implemented my own layer on top of uom's `from_str` to relax the requirement for a space, but there is no way for me to make it work for full units without manually listing all of the units in my code because uom doesn't seem to provide any functionality to work with full unit strings rather than abbreviations.

Could uom provide a function like `Mass::from_str_unit(100.0f64, "grams") -> Result<...>` (which would also accept "gram" and "g", but also "pounds" and "kg" and so on)? From my perspective, this would actually be better than changing `from_str`, as it makes it possible for me to implement my own human-friendly parsing code without needing to incorporate my opinions about human-friendly parsing into uom itself.

If this is not practical, could the `from_str` implementation be extended to allow the singular and plural units? Right now my human-friendly parsing layer works by creating a temporary string which does fit uom's desired format and then asking uom to parse that.

**Comment by iliekturtles** [comment]
Adding descriptions to the current `FromStr` impl is probably a good start (PRs welcome). I would like to keep one parsing method that only accepts input based on SI conventions (see [this](https://www.nist.gov/pml/special-publication-811/nist-guide-si-chapter-6-rules-and-style-conventions-printing-and-using) for one reference). A second could work with less precise input that would be more human friendly like you describe.

I took a brief look at `std::str` and it looks like `FromStr` is the only relevant trait in the standard library. Did I miss one? If making the split described above should `FromStr` be the strict or human parsing method?

**Comment by bheisler** [comment]
FromStr is the only built-in parsing trait, yes. In my project I have my own second trait for providing more human-friendly parsing, but of course I don't expect uom to implement that; I'm just hoping for uom to expose some helpful functions that would make it easier for me to implement it myself.

I think Rust's documentation isn't entirely clear on how lenient or strict the FromStr implementation should be, so I think that decision should be left up to you. For my particular project, I need to define my own parsing regardless.

If I understand the code correctly, I think that all I'd need to do in order to add support for the singular and plural form of the unit is to add a few extra cases to the match in the macro that generates the quantities, is that correct? I can probably send a PR in the next few days.

**Comment by iliekturtles** [comment]
I believe you're correct about just adding cases to the `FromStr` implementation. I took a brief look this morning and if you can submit a PR I'll review in more detail.

I also just started reading your "Building a Recipe Manager - Part 2" post. I'm eager to get feedback from others who are using the `uom`, so please keep submitting issues, even for simple things.

**Comment by iliekturtles** [comment]
I had another thought about parsing. Similar to how `Arguments`/[`QuantityArguments`](https://docs.rs/uom/0.30.0/uom/si/fmt/struct.QuantityArguments.html) is used to apply `uom`-specific settings to formatting, marker structs could be used to implement different parsing rules (strict, human readable, ...). I had originally hoped to embed all the options into struct properties, but `FromStr`'s limitations don't make this possible.

```rust
let result = HumanReadableQuantity::from_str("...");
let quantity = result?.into();
```

As an aside, see https://github.com/iliekturtles/uom/pull/90 for the full discussion around the current implementation.

**Comment by bheisler** [comment]
If you'd like to add user-definable parsing, I wouldn't do that using the `FromStr` trait. Consider the Chrono crate, which provides functions like [`DateTime::parse_from_str(s: &str, fmt: &str)`](https://docs.rs/chrono/0.4.19/chrono/struct.DateTime.html#method.parse_from_str).

**Comment by bheisler** [comment]
With that PR merged, this is done (from my perspective). You discussed potentially doing other work, though, so I'll leave this issue open just in case you'd like to use it to coordinate that.

**Comment by iliekturtles** [comment]
Thanks for the confirmation. I thought about keeping the issue open for a while, but since we don't have any specific requirements at this point I'm going to close.
