### ISSUE TITLE
Rename use_serde feature?

### ISSUE THREAD

**Issue by iliekturtles** [iliekturtles/uom#216]
This would be a breaking change. See https://blog.turbo.fish/cargo-features/ for details how to enable this. I'm partial to the idea of a better feature name and `uom` is not yet committed to backwards compatibility, but this may end up being a larger hassle for users that it's worth.

**Comment by Aehmlo** [comment]
Is there any reason `uom` couldn't support both feature names? Then there could potentially be a soft-deprecation for the time being.

**Comment by iliekturtles** [comment]
Both could definitely exist and we could probably add a warning that `use_serde` is being used instead of `serde`.

**Comment by iliekturtles** [comment]
https://github.com/iliekturtles/uom/blob/a77ef61e8db72cbdef40fabddeb0ed3506ad5ebc/src/tests/system.rs#L540-L543

`Num` crates use `Serde` 1.0 now. It also looks like all of the `uom` internal code checks for the `"serde"` feature which doesn't actually exist!

**Comment by therealfrauholle** [comment]
As far as I understand, with the introduction of namespaced features and weak dependencies as of https://github.com/rust-lang/cargo/pull/10269 it is now much easier to implement and does not require re-exports as of the mentioned blog post. This feature moved to stable as of rust 1.60.0

So if the plan is ever to bump the MSRV, I guess it is time for deprecation now.

**Comment by iliekturtles** [comment]
I'm interested in bumping the MSRV (#239) but I'm a bit hesitant to go all the way to 1.60 when the work-arounds to resolve this issue aren't too painful and allow for an older MSRV. I don't have a specific policy about when to update the MSRV and what version to jump to so I'm interested in hearing thoughts about going all the way to 1.60.

**Comment by iliekturtles** [comment]
MSRV bumped to 1.60.0 in #422. I haven't started looking at this issue yet.
