### ISSUE TITLE
Feature request (or help request)

### ISSUE THREAD

**Issue by Lucretiel** [iliekturtles/uom#219]
Is it possible to instantiate a `Quantity` with a known type but a runtime unit of measure? For instance, suppose I have the float value `2.5` and the string `"km"`. Is there any way to parse that aside from formatting the quantity *back* into a string and using `FromStr`? If not, this is a feature request from a constructor or an enum of different unit measures of a each type that can be parsed and used to construct quantities.

**Comment by iliekturtles** [comment]
There isn't a way to do this right now and two issues prevent it: there isn't a way to just parse `"km"` into the appropriate unit and there is no `new` constructor that can take a unit at runtime. I just added #220 to resolve the former and #91 is open to resolve the later. The recent merge of #215, which added the `Unit` enum, should make both of these possible.

Let me know if the resolution of those two issues will resolve your problem so we can mark this issue complete.

**Comment by Lucretiel** [comment]
Yup, those will definitely cover it!

**Comment by Lucretiel** [comment]
I suppose a stopgap solution would be to parse "1 {unit}" and multiply by the untyped quantity

**Comment by iliekturtles** [comment]
Marking this issue closed since the other two cover the functionality needed. Please re-open if I missed anything!

**Comment by Lucretiel** [comment]
For those finding there way here looking for a way to do this before the features land, I've found that `format("1.0 {unit}", unit=unit_str).parse()` works perfectly.
