### ISSUE TITLE
Using uom type as member of a struct

### ISSUE THREAD

**Issue by davidwalschots** [iliekturtles/uom#230]
Despite reading the documentation, I'm unable to figure out how to use `uom` as members of a struct. The following code doesn't compile with the following error on the member declaration line:

> wrong number of type arguments: expected 2, found 0 expected 2 type arguments

It seems the following generic types are needed: 
* U: Base units.
* V: Underlying storage type.

Could you provide some insight into how to declare a member of a struct?

```rust
pub struct Generator {
    potential: ElectricPotential,
}

impl Generator {
    pub fn new() -> Generator {
        Generator {
            potential: ElectricPotential::new::<volt>(0.),
        }
    }
}
```

**Comment by iliekturtles** [comment]
There are a number of different type aliases for `ElectricPotential` (https://docs.rs/uom/0.30.0/uom/?search=electricpotential). Looks like you're using the alias in the `uom::si::electric_potential` mod right now. Generally you'll want one of the aliases from one of the underlying storage type modules, e.g. `uom::si::f32::ElectricPotential`.

**Comment by davidwalschots** [comment]
Thank you. That's clear. The `rust-analyzer` extension for vscode was confusing me, as that extension for some reason shows an unresolved import error when writing `use uom::si::f32::ElectricPotential;` even though the code compiles fine.
