### ISSUE TITLE
Question about Q! and mks.rs example

### ISSUE THREAD

**Issue by ryanpeach** [iliekturtles/uom#248]
In this example:

https://github.com/iliekturtles/uom/blob/master/examples/mks.rs

What does this set of lines do?

```rust
mod f32 {
    mod mks {
        pub use super::super::*;
    }

    Q!(self::mks, f32);
}
```

And then once I am done writing this file in my own project, do I import the quantities like so?

```rust
use crate::quantities::or::whatever::{Quantity1, Quantity2}
```

If not then how do I import them?

Just a few questions its not really clear.

**Comment by iliekturtles** [comment]
`mod f32` and the containing code sets up quantity type aliases that use `f32` as the underlying storage type. By default the `system!` macro only sets up [type aliases](https://docs.rs/uom/0.31.1/uom/si/length/type.Length.html) with the base units and storage type missing. The `Q!` macro in this example, equivalent to [`ISQ!`](https://docs.rs/uom/0.31.1/uom/macro.ISQ.html) in the built-in `SI` system, creates [type aliases](https://docs.rs/uom/0.31.1/uom/si/f32/type.Length.html) using the default base units (meter, kilogram, second) and `f32` as the storage type.

For the mks example the use statement is `use crate::f32::{Length, Mass, Time};`.

You can also look at the code in the built-in `SI` system:

https://github.com/iliekturtles/uom/blob/e10817587ade570c1e30d8a3afb8c4dcc6800a9b/src/si/mod.rs#L105-L116

The first `ISQ!` invocation creates type aliases in the `quantities` module with the base units defined but no underlying storage type. The `storage_types!` macro calls `ISQ!` for each enabled storage type (see the available crate features). `storage_types!` essentially expands to:

```rust
mod f32 {
    pub type V = f32;
    ISQ!(crate::si, V);
}
mod f64 {
    pub type V = f64;
    ISQ!(crates::si, V);
}
// ... and so on for all enabled storage types.
```

Please let me know if this makes sense. I also welcome any suggestions about how to incorporate this information into the documentation.

**Comment by ryanpeach** [comment]
That makes perfect sense and I think I’d just link to this description to explain that. Thanks
