### ISSUE TITLE
How to define a "tick" unit?

### ISSUE THREAD

**Issue by nbigaouette** [iliekturtles/uom#249]
I am not sure how to phrase my question... I'll try to explain as clearly as possible!

I am using uom in a project of mine where I have motors that rotate. Those motors are controlled by telling them their required velocity in terms of "ticks per second" and acceleration in terms of "ticks per second^2" (as float values) where a "tick" (or "step") is the smallest angle the motor can rotate.

A motor will have a well defined number of ticks per rotation, but this number can change with different motors (or even config). I thus load this from a config file at runtime.

How can I define a "length", "velocity" and "acceleration" in units of "ticks", "ticks/second" and "ticks/second^2"?

I _think_ I must define a new "length" unit using the `unit!()` macro, but it needs a base in meter, for which I don't have since the value is dynamic. Or should a different approach be tried?

Is that possible?

Thanks!!

**Comment by iliekturtles** [comment]
If a tick is the smallest angle the motor can rotate then you'll want to use `Angle`, `AngularVelocity`, and `AngularAcceleration` rather than `Length`, `Velocity`, and `Acceleration`. If the number of ticks is specified at runtime you can't use `unit!` to create a new unit. `unit!` creates the new unit at compile time.

I think you'll want to load the motor's revolutions per tick into an `Angle` value. You can then use this value to convert between a number of ticks and rotational values.

```rust
let rev_per_tick = Angle::new::<revolution>(load_revolutions_per_tick_from_config());
let ticks: f32 = 100.0;
let t = Time::new::<second>(1.0);
let motor_angular_velocity = ticks * rev_per_tick / t;
let motor_frequency = motor_angular_velocity / rev_per_tick;
```

**Comment by nbigaouette** [comment]
Ok thanks for the idea, I'll try this.

What I am not sure is that the number of ticks is the final value that needs to be calculated, not the initial input. So I need to go from a `Length` of cable to a number of ticks of rotation of the motor.

So my parameters are the pulleys diameter and ticks per revolution (from the config file). The input is the length of cable to wind and the output is the number of ticks that the motor needs to turn. I then send a command to the motor in units of ticks.

I will try to work this out. Thanks!

**Comment by iliekturtles** [comment]
This should do it:

```rust
let pulley_diameter = Length::new::<meter>(load_pulley_diameter_from_config());
let revolutions_per_tick = Angle::new::<revolution>(1.0 / load_ticks_per_revolution_from_config());
let length_to_wind = Length::new::<meter>(read_length_from_input());

let pulley_circumference = std::f32::consts::PI * pulley_diameter;
let length_per_tick = revolutions_per_tick * pulley_circumference;

let ticks_as_ratio = length_to_wind / length_per_tick;
let ticks_as_f32: f32 = ticks_as_ratio.into();
```

**Comment by wucke13** [comment]
I think this can be closed @nbigaouette ?
