### ISSUE TITLE
Feature request: Add MolarHeatCapacity unit

### ISSUE THREAD

**Issue by nakedible** [iliekturtles/uom#262]
Trivial to add to SI, unit is "joule per kelvin per mole": https://en.wikipedia.org/wiki/Molar_heat_capacity

```
type MolarHeatCapacity = Quantity<ISQ<P2, P1, N2, Z0, N1, N1, Z0>, SI<f64>, f64>;
```

This is the unit of the [Gas Constant](https://en.wikipedia.org/wiki/Gas_constant) used in [Ideal Gas Law](https://en.wikipedia.org/wiki/Ideal_gas_law).

**Comment by iliekturtles** [comment]
I'll try to get to this in the next few days!
