### ISSUE TITLE
How to raise a Quantity to a power?

### ISSUE THREAD

**Issue by ammon0** [iliekturtles/uom#267]
As for example, finding an area:
```
extern crate uom;

use uom::si::f32::Length;
use uom::si::length::kilometer;

fn main() {
	let l = Length::new::<kilometer>(5.0);
	let area = l.powi(2);
	println!("The area is {:?}", area);
}
```
Fails to compile with:
```
error[E0277]: cannot multiply `PInt<UInt<UTerm, B1>>` by `{integer}`
 --> src\main.rs:8:15
  |
8 |     let area = l.powi(2);
  |                  ^^^^ no implementation for `PInt<UInt<UTerm, B1>> * {integer}`
  |
  = help: the trait `std::ops::Mul<{integer}>` is not implemented for `PInt<UInt<UTerm, B1>>`

error[E0277]: the trait bound `{integer}: Integer` is not satisfied
 --> src\main.rs:8:20
  |
8 |     let area = l.powi(2);
  |                       ^ the trait `Integer` is not implemented for `{integer}`
  |
  = help: the following implementations were found:
            <NInt<U> as Integer>
            <PInt<U> as Integer>
            <Z0 as Integer>
```
Is this possible? If so, is the correct way to do it documented somewhere? How can I know which operations, say from [here](https://doc.rust-lang.org/nightly/std/primitive.f64.html), can be applied to a Quantity, and which cannot?

**Comment by adamreichold** [comment]
As raising a quantity to a power changes the unit and the unit is a compile-time property, the exponent itself needs to be available at compile-time, i.e. one has to use the compile-time integers of the [`typenum`](https://crates.io/crates/typenum) crate:
```rust
use uom::si::f32::Length;
use uom::si::length::kilometer;
use uom::typenum::P2;

fn main() {
    let l = Length::new::<kilometer>(5.0);
    let area = l.powi(P2::new());
    println!("The area is {:?}", area);
}
```

The exponent is still passed as a singleton value representing the type as this is easier to read than the turbo-fish notation.

The docs do have [an example of this](https://docs.rs/uom/0.31.1/uom/si/struct.Quantity.html#method.powi), but I suspect that it is drowned in the complicated type signature of the method.

**Comment by iliekturtles** [comment]
I can't do anything about the type signature at this point, but do either of you think it would helpful to pull the `uom::typenum::P2` reference out into a using?

```rust
use uom::typenum::P2;

let a: Area = Length::new::<meter>(3.0).powi(P2::new());
```

**Comment by ammon0** [comment]
Well, now it seems obvious. I don't know how I missed the powi() documentation. I also didn't know you were re-exporting typenum.
