### ISSUE TITLE
TryFrom<Duration>  for Time has conversion bug

### ISSUE THREAD

**Issue by T-Bakker** [iliekturtles/uom#280]
Hi,

The released version 0.31.1 has a issue with the conversion of Duration to Time as the Duration is extracted as micros instead of nanos. This results in the sub-second aspect of the duration being off by a factor of 1000.

This bug is fixed in [8adc731f6c754ef14f07bd83827c909f2a7da25f](https://github.com/iliekturtles/uom/commit/8adc731f6c754ef14f07bd83827c909f2a7da25f#diff-5705f43323810e3c6ab6fae2a60720967e15bcc266cd5106468126dc9e773474L127-R127), but that change is not released as the released version still has the bug: https://docs.rs/uom/latest/src/uom/si/time.rs.html#132.

Would it be possible to create a bugfix release with this change?

**Comment by iliekturtles** [comment]
Good timing! I was writing up release notes as you submitted this issue! The first draft is available for review at #281. I'll make an update to the notes to explicitly call out the `Duration`/`Time` conversion fixes.

**Comment by iliekturtles** [comment]
[v0.32.0](https://crates.io/crates/uom) published with this fix!

**Comment by T-Bakker** [comment]
Hi,

That is awesome! Good timing indeed, what a coincidence.

Thank you for the credits in the changelog, it is an honour :).
