### ISSUE TITLE
Suport .exp() for Ratio

### ISSUE THREAD

**Issue by jacg** [iliekturtles/uom#290]
Is there any reason not to support `.exp()` for `Ratio`?

If not, I'd be happy to submit a PR.

**Comment by iliekturtles** [comment]
See #11. Looks like I punted on implementing `exp` way back when. A PR to add `exp` for `Ratio` would be welcome. Check out some of the inverse trig functions like `acos` for similar `Ratio`-only functions. I believe `exp` will also be `std` only.

**Comment by iliekturtles** [comment]
> Presumably `exp2`, `ln`, `log` etc. are missing for the same reason, and could be added in the same PR?

Yep. Go ahead and add to this PR if that works for you.
