### ISSUE TITLE
Frequency quantity

### ISSUE THREAD

**Issue by iliekturtles** [iliekturtles/uom#30]
Add frequency quantity and associated units.

**Comment by Aehmlo** [comment]
What more units would you like to see added? I'd be hesitant to include such things as angular frequencies, since it's easy to misuse that, but I'm not sure what other frequency units would be useful.

**Comment by iliekturtles** [comment]
Invert some of the [time](https://www.nist.gov/pml/nist-guide-si-appendix-b9-factors-units-listed-kind-quantity-or-field-science#TIME) units and add cycles per day/hour/minute/year.

**Comment by Aehmlo** [comment]
As far as nomenclature goes, would you prefer e.g. `per_hour`, `inverse_hour`, or another style (`cycles_per_hour` comes to mind, but I'm again leery of that due to the possible 2π multiplier and the non-unit radian, which it seems we might want to keep out of the unit of measure crate).

**Comment by iliekturtles** [comment]
I think `cycles_per_hour` with an abbreviation of `1/h` sounds best. This also seems to be most consistent with SI which used to use "cycles per second" before adopting `Hz`.

I still need to figure out how to deal with different quantities that have the same dimension (see #3). Frequency and angular frequency fall into this category and ideally the solution will ensure that units for these different quantities fall into different enums.
