### ISSUE TITLE
Support for rational powers?

### ISSUE THREAD

**Issue by gonzaponte** [iliekturtles/uom#302]
While playing around with `uom`, I noticed that it's not possible to perform an `sqrt` operation on a quantity with an odd power of a dimension. I have a specific case in which this feature is slightly troublesome and another more general case.

Specific case:
The spatial probability distribution of electrons drifting in a medium under an electric field is modeled by a gaussian distribution with a width proportional to the sqrt of the drift distance. Also, the proportionality factor has dimensions `[L]^1/2`. To obtain the width, we multiply two quantities with dimension `[L]^1/2` to get a quantity of dimension `[L]`. Naturally, we can solve this case easily by doing `sqrt([L] · [L])`...

...which brings me to the more general issue:
There are plenty of empirical relationships or data parametrizations to obtain some quantity based on other measured quantities. Typically `y = A · x^B` with `B` not necessarily an integer. In this case, the dimensions of `A` are arguably unphysical, but this provides a necessary correlation between the two quantities.
This type of equations usually rely on `x` and `y` being in specific units, so perhaps it's always necessary to work with dimensionless values like `y = <unit of y> · A · (x / <unit of x>)^B`, where `A` is now dimensionless.

Does it make sense to add support for these cases? Any thoughts on how to deal with them in general?

**Comment by iliekturtles** [comment]
Thanks for submitting the issue. The need for rational powers came up a bit ago and is being tracked in #221 (took me a while find this and I knew it existed). Do you expect that rational powers will support your general case noted above? If so do you agree we can close this issue as a duplicate?

**Comment by gonzaponte** [comment]
Indeed, having `powf` implemented would address it. I hadn't seen it. This can be closed.

**Comment by iliekturtles** [comment]
Thanks for reviewing. I updated #221's description to explicitly call out the need for rational powers.
