### ISSUE TITLE
Add "particles" as a unit of measure for amount of substance

### ISSUE THREAD

**Issue by crystal-growth** [iliekturtles/uom#317]
It might be nice to extend the amount of substance units with "1 particle (atom/molecule/electron)" unit, 
being equivalent to 1 mole / N_avogadro.

It will be useful for example in:

-  semiconductor physics, where carrier density is usually measured in [electrons per cm3], and the doping level in [dopant atoms per cm3], 
-  nuclear physics (neutron flux [neutrons per m2 per second]), etc.
-  measuring density of non-molecular species like [bacteria per m2 of surface] 

Affected quantities are amount_of_substance, catalytic_activity_(concentration) and molar_(concentration | mass | energy | heat_capacity).

**Comment by iliekturtles** [comment]
Thanks for submitting this issue. This is a good idea.

I'm trying to get through the PR backlog so it will be a bit before I could get to this. A PR to add particle and other related units would be very welcome.
