### ISSUE TITLE
Enthalpy and Entropy

### ISSUE THREAD

**Issue by jfkonecn** [iliekturtles/uom#375]
I'm planning on using this library for some thermodynamic calculations. I will need to perform some calculations involving enthalpy (J / kg) and entropy (J / (kg * K)) 

It looks like the calculations can be done using the existing code base, but I also want to give my users the ability to input the value for entropy and enthalpy with a dropdown to select the units.

I was planning on using the uom::si::<some_unit>::units() function followed by a call to the abbreviation function to populate the dropdown. To parse the user selection I was going to use the uom::si::<some_literal>::<some_unit>::from_str function.

Is there a way to create abbreviations for derived units in the current code base?

I think might be a duplicate of #357, but I wasn't sure if you were also going to account for the abbreviation function.

**Comment by iliekturtles** [comment]
As you have found out, you can use those quantities that aren't explicitly defined. Unfortunately there isn't any way to add units for quantities that are not explicitly defined. I think the best solution here is to add both quantities. These should both be relatively straight forward quantities to add. See https://github.com/iliekturtles/uom/blob/master/src/si/energy.rs for an example that can be followed.

**Comment by jfkonecn** [comment]
thanks!
