### ISSUE TITLE
Is a "Cycle" (or something similar) quantity reasonable?

### ISSUE THREAD

**Issue by zmjackson** [iliekturtles/uom#379]
In my application I need a quantity for CPU ticks. That seemed too specific to me, so I thought something like "cycles" might be more generally useful to represent the concept.

Before I put a PR together I figured I'd ask whether that is reasonable, or if there is a suggested alternative.

Thanks!

**Comment by iliekturtles** [comment]
What underlying Si units are you looking to use? Frequency (s⁻¹) already has a number of `hertz1 and `cycle_per_*` units.

**Comment by zmjackson** [comment]
I agree that it doesn't necessarily fit within the SI units. Frequency is not appropriate because that implies a "per unit time." I think I would be better off creating my own system for this project. Thanks!
