### ISSUE TITLE
Conversion factor doc inconsistency

### ISSUE THREAD

**Issue by NiklasVousten** [iliekturtles/uom#424]
The documentation stated that Conversion is handled like this: ```(value * coefficient()) + constant()```

But using this code snipped for a manual conversion like Fahrenheit to Kelvin this breaks:
```rust
fn test() {
    let f: f32 = 2.0;
    let k = convert::<uom::si::thermodynamic_temperature::degree_fahrenheit>(f);
    println!("{k:?}");
}

fn convert<N>(value: f32) -> f32
where
    N: uom::Conversion<f32, T = f32>,
{
    (value * N::coefficient()) + N::constant(uom::ConstantOp::Add)
}
```

The result is ```460.78113```, but 2 degrees Fahrenheit is ```256.483```

Rewriting the equation to ```(value + constant()) * coefficient()``` results in ```256.48337```

So there is an inconsistency between code and documentation.

**Comment by iliekturtles** [comment]
Good catch. The actual code to convert to from a given unit to the base unit is in the `to_base` function linked below and essentially does `(value + constant()) * coefficient()` as you noted. The more complex formula in the code is to handle floating point precision issues and non-standard base units.

A PR to update the documentation for the `Conversion` trait is welcome.

https://github.com/iliekturtles/uom/blob/6d34c3e55181f3e83b98474d5f5a03a426a23afc/src/system.rs#L328-L357

Converting from a base unit to a given unit essentially does `(value * coefficient()) - constant`.

https://github.com/iliekturtles/uom/blob/6d34c3e55181f3e83b98474d5f5a03a426a23afc/src/system.rs#L297-L326
