### ISSUE TITLE
Change of base_unit of Ratio quantity

### ISSUE THREAD

**Issue by igiona** [iliekturtles/uom#451]
Hi

I'm facing issues with the precision, because of [the fact that uom stores the values in the base unit](https://docs.rs/uom/latest/uom/#design).

I see that you can change the [ISQ](https://docs.rs/uom/latest/uom/macro.ISQ.html) units, but I need to change the base unit of the `Ratio` type to `percentage` and other SI units.
Is this feature supported? If yes, how can it be done?

Thank you
ig

**Comment by iliekturtles** [comment]
Unfortunately, this isn't supported. In some future version of `uom` I plan to have types to allow you to store non-normalized units. For the time being there are no plans to allow for normalizing to an arbitrary unit.
