### ISSUE TITLE
NIST Special Publication link

### ISSUE THREAD

**Issue by elsandosgrande** [iliekturtles/uom#471]
It seems that the URI of Appendix B9 of the NIST Special Publication 811 has been changed to https://www.nist.gov/pml/special-publication-811/nist-guide-si-appendix-b-conversion-factors/nist-guide-si-appendix-b9. At the very least, I got a 404 when clicking the corresponding link in `README.md` and `CONTRIBUTING.md`.

**Comment by iliekturtles** [comment]
Thanks for the report. Fixed in #478 and #481.
