### ISSUE TITLE
Adding a function to angle to reduce it to the princlple domain [0, 2𝜋) radians

### ISSUE THREAD

**Issue by tedgin** [iliekturtles/uom#490]
When working with angles, it is often useful to convert their values to the principle domain [0, 2𝜋) radians. For examples, an angle of 540 degrees would be converted to 180 degrees, and an angle of -90 degrees would be converted to 270 degrees. This is different from the existing `Angle::fract::<revolution>()`, which returns the fractional part of a revolution. `fract::<revolution>()` maps -90 degrees to -90 degree. 

Would a function like this make sense in uom? If so, I'm willing to submit a PR.

**Comment by iliekturtles** [comment]
Looks like this would be [`rem_euclid`](https://doc.rust-lang.org/std/primitive.f32.html#method.rem_euclid). PR would be very welcome!
