### ISSUE TITLE
num dependency should have default-features=false

### ISSUE THREAD

**Issue by radix** [iliekturtles/uom#53]
My application which uses uom doesn't need additional `num-*` crates. Given that num has optional dependencies which are enabled by default, I tried setting `default-features = false` in my Cargo.toml, but the default features were still enabled. I eventually figured out that this is because `uom` is depending on `num` without specifying `default-features = false`.

**Comment by radix** [comment]
ok, I was apparently looking at the wrong Cargo.toml -- uom's dependency on num does have default-features = false :P sorry for the noise.

**Comment by radix** [comment]
ok, so it's going to be a little more involved than just a change to the Cargo.toml ;-)


BTW, the reason I'm poking at this situation is because I'm running into some extreme performance problems in some code I recently ported to uom, and a profile turned up a bunch of num-rational code in a codepath that's doing a lot of equality checks on my Quantities. The strange thing is that I am not intentionally using rationals in my code anywhere... so while I would like to remove these spurious dependencies from my app, the real thing I'm trying to figure out is why this code is being invoked at all. I may end up filing another uom bug about this once I figure out more.

**Comment by iliekturtles** [comment]
Rationals are used in intermediate calculations to hold conversion factors for integer storage types. Likely the compiler isn't able to factor this out at compile time like it is for floating point types. Using the play-pen to mock up `change_base` may be able to show what is happening. This may require specialization or const fn to be stabilized to generate optimal code for integer types.

Would still be good to see if fewer `num` features/crates can be included.

**Comment by radix** [comment]
I see. I didn't realize that even stuff like Eq is compatible with non-Self quantities.

I guess I'll just have to avoid using uom in these cases where the performance matters: one of my simple pathfinding tests went from unnoticeable runtime to 100 seconds.

**Comment by radix** [comment]
Ok, I opened #54 and am closing this.
