### ISSUE TITLE
Using storage_types macro requires defining crate features

### ISSUE THREAD

**Issue by Nemo157** [iliekturtles/uom#61]
`storage_types!` uses `#[cfg(feature = "u32")]` internally to enable and disable different storage types. Unfortunately this is non-hygenic and depends on the features of the crate _calling_ `storage_types!`, not the features of `uom`.

The workaround is to just add a default `u32` (or whichever storage type you want) feature to the crate that calls the macro as well.

I don't know if there's a simple solution to this problem currently, hopefully Macros 2.0 might allow hygenic `cfg` attributes?

**Comment by iliekturtles** [comment]
Good point! I haven't really followed what changes will be happening in Macros 2.0 so I'm not sure if that will have a solution to the issue. As a first step I'll add additional documentation to the macro to mention this limitation (PRs also welcome).

A possible solution without Macros 2.0 is to move `#cfg` attributes out of the match bodies and on to match arms. Not sure if this will work for sure but this may make the `#cfg` attributes apply in the `uom` crate before the macro is executed by the calling crate.

**Comment by Nemo157** [comment]
> A possible solution without Macros 2.0 is to move `#cfg` attributes out of the match bodies and on to match arms.

That was my first thought, but it doesn't look like `macro_rules!` allows attributes on the match arms.

**Comment by Nemo157** [comment]
I think it's actually the modularization changes for Macros 2.0 that would easily allow fixing this, the helper arms of the `storage_types!` macro could be split out into separate macros that could then be `cfg`ed out, e.g. somewhat like

```rust
#[cfg(feature = "u8")]
macro storage_type_u8($(#[$attr:meta])*) @$M:ident ($($tt:tt)*)) {
    storage_type!(@$M $(#[$attr])* u8, u8; $($tt)*);
}

#[cfg(not(feature = "u8"))]
macro storage_type_u8($(#[$attr:meta])*) @$M:ident ($($tt:tt)*)) {
}
```

which `storage_types!` could then delegate to hygienically.

Taking another look at the Macros 2.0 tracking issue, it doesn't sound like it's coming anytime soon though. I'm going to have an attempt at coming up with a solution that works with `macro_rules!`.
