### ISSUE TITLE
Add support for i128/u128

### ISSUE THREAD

**Issue by iliekturtles** [iliekturtles/uom#85]
Add support for `i128`/`u128` now that both types are stable. This may be blocked by the num-* crates which may not support these types. Leave types out of CI build scripts for the moment. A larger effort to better support different `rustc` versions will need to be done.

**Comment by Aehmlo** [comment]
I think we [should be good](https://github.com/rust-num/num-traits/commit/f4125621acd7d3bd9da7a29a68d97b3aec177780) on the other crates.

**Comment by Aehmlo** [comment]
I think this is was what I was thinking of in #150, for what it's worth.

**Comment by iliekturtles** [comment]
`i128`/`u128` were stabilized in 1.26.0. Now that `uom` requires 1.28.0 these can be added without any version checking!
